apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-secret
  #  namespace: '{{ .Release.Name }}-scl-namespace'
data:
  YPS_SERVICE_NAME: 'yps.{{ .Release.Name }}-scl-namespace:8080/YPServer'
  YPS_DB_URL: 'jdbc:mysql://yps-db.{{ .Release.Name }}-scl-namespace:3306/YPS'
  DB_CONNECTION_TIMEOUT: '120000'
  DB_VALIDATION_TIMEOUT: '40000'
  DB_IDLE_TIMEOUT: '600000'
  DB_LEAK_DETECTION_THRESHOLD: '0'
  DB_MAX_LIFETIME: '1800000'
  DB_MAX_POOL_SIZE: '75'
  DB_MIN_IDLE_TIMEOUT: '25'
  USE_PROXY : 'false'
  PROXY_HOST : ''
  PROXY_PORT : ''
  SCC_REG_ID : '{{ .Values.vpc_prefix }}-{{ .Values.deployment_type }}-scc'
  SCC_SECRET_KEY : '9aocilvn7bxdd11d'
  SCC_SECRET_KEY_ID : '2079535239'
  WEBPA_REG_ID : '{{ .Values.vpc_prefix }}-{{ .Values.deployment_type }}-wpa'
  WEBPA_SECRET_KEY : '1gfsx0yb6p2rtsw5'
  WEBPA_SECRET_KEY_ID : '7743160535'
  WEBPA_SERVICE_PUBLIC_URL : 'https://{{ .Values.vpc_prefix }}.{{ .Values.deployment_type }}.{{ .Values.root_domain }}/wpa'
  AUTH_SERVER_PUBLIC_URL : 'https://{{ .Values.vpc_prefix }}.{{ .Values.deployment_type }}.{{ .Values.root_domain }}/scc'
  EMS_ENABLE_PROXY: 'false'
