apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-secret
    labels:
      app.kubernetes.io/name: {{ include "yps-app.name" . }}
      helm.sh/chart: {{ include "yps-app.chart" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      #namespace: '{{ .Release.Name }}-scl-namespace'
type: Opaque
stringData:
  yps_username: "{{ .Values.database.username }}"
  yps_password: "{{ .Values.database.password }}"

